name: safex
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  modal_progress_hud: ^0.1.3
  qr_flutter: ^4.0.0
  barcode_scan_fix: ^1.0.2
  provider: ^5.0.0
  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  email_validator: ^2.0.1
  android_intent: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - images/male/
    - images/female/
    - images/
  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: New Tegomin
      fonts:
        - asset: fonts/NewTegomin-Regular.ttf

